Random Forest using MCC/SCLC Tumor Data applied to MCC/UISO lines
========================================================

```{r, echo=FALSE}
# Here's how to compile this file in R, assuming your current directory is the repository root:

# library(knitr)
# knit("./reports/randomForest.Rmd", encoding="utf-8")
```

```{r, echo=FALSE, message=FALSE}
require(ggplot2)
require(plyr)
require(xtable)
options(xtable.type="html")
```

```{r load, echo=FALSE, error=FALSE, warning=FALSE, cache=FALSE, message=FALSE}
load("../cache/rf.eset.RData")
load("../cache/rf.predict.RData")
load("../cache/rf.eset.unsupervised.RData")
load("../cache/classes.train.RData")
load("../cache/classes.train.unsupervised.RData")
load("../cache/samplenames.train.RData")
load("../cache/samplenames.train.unsupervised.RData")
```

## Cancer Type Error Rate
```{r echo=FALSE, results='asis'}
tmp <- data.frame(table(classes.train))
class.err.rate <- as.numeric(tail(rf.eset$err.rate,1))[-1]
tbl <- data.frame(Frequency=tmp$Freq, Error=class.err.rate)
rownames(tbl) <- tmp$classes.train
print(xtable(tbl))
```

## Confusion Matrix
```{r confusionmatrix, echo=FALSE, results='asis'}
print(xtable(rf.eset$confusion)) # , digits=c(rep(0, 11), 2)
``` 

## Average test set prediction error
``` {r testerror, echo=FALSE, results='asis'}
rf.predict.mean <- ddply(rf.predict, "class", function(x) data.frame(MCC=mean(x$MCC), SCLC=mean(x$SCLC)))
rf.predict.mean.xtable <- xtable(rf.predict.mean)
print(rf.predict.mean.xtable)
```

## Average OOB Votes (Per Class)
```{r avgvotestbl, echo=FALSE, results='asis'}
oobvotes <- data.frame(rf.eset$votes, cancertype=classes.train)
avgoobvotes <- ddply(oobvotes, .variables="cancertype", function(x) colMeans(x[, -ncol(x)]))
rownames(avgoobvotes) <- avgoobvotes[, 1]
avgoobvotes <- avgoobvotes[, -1]
colnames(avgoobvotes) <- levels(classes.train)
print(xtable(avgoobvotes, digits=2))
```

## Multi-Dimensional scaling plot of random forest proximities
```{r mdsrfallcelllines, fig.width=12, fig.height=12, echo=FALSE}

rf.mds <- cmdscale(1 - rf.eset.unsupervised$proximity, eig=TRUE)

plotdata <- data.frame(x=rf.mds$points[,1], y=rf.mds$points[,2],
                       labels=samplenames.train.unsupervised, cancertype=classes.train.unsupervised)
p <- ggplot()

p <- p + geom_point(data=plotdata, aes(x=x, y=y, 
                                       color=cancertype),
                    size=5, show_guide=TRUE)

p <- p + scale_colour_brewer("Cancer type", palette="Set1")
p <- p + scale_shape_manual("Sample type", values=c(18,16))

p <- p + geom_text(data=plotdata, aes(x=x, y=y, label=rownames(plotdata)),
                   hjust=1.0, vjust=-1.25, size=4)

p <- p + labs(x="Scaling component 1", y="Scaling component 2")
p <- p + theme_bw() + theme(legend.position=c(0.85,0.5),
                            legend.title=element_text(size=14),
                            legend.text=element_text(size=12),
                            legend.background=element_rect(colour="black"),
                            panel.background = element_rect(fill = "#FFFFFF"))
print(p)

# # for publication
# ggsave("figure/mdsrfallcelllines.pdf", width=8, height=8)
```
